version: 2
updates:
- package-ecosystem: gitsubmodule
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: staging
- package-ecosystem: pip
  directory: "/src/python"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: staging
  ignore:
  - dependency-name: boto3-stubs[essential]
    versions:
    - 1.16.61.0
    - 1.16.62.0
    - 1.16.63.0
    - 1.17.0.0
    - 1.17.1.0
    - 1.17.10.0
    - 1.17.11.0
    - 1.17.12.0
    - 1.17.13.0
    - 1.17.14.0
    - 1.17.15.0
    - 1.17.16.0
    - 1.17.17.0
    - 1.17.18.0
    - 1.17.19.0
    - 1.17.2.1
    - 1.17.20.0
    - 1.17.21.0
    - 1.17.22.0
    - 1.17.23.0
    - 1.17.24.0
    - 1.17.25.0
    - 1.17.26.0
    - 1.17.27.0
    - 1.17.28.0
    - 1.17.29.0
    - 1.17.3.0
    - 1.17.30.0
    - 1.17.32.0
    - 1.17.33.0
    - 1.17.34.0
    - 1.17.35.0
    - 1.17.36.0
    - 1.17.38.0
    - 1.17.39.0
    - 1.17.4.0
    - 1.17.40.0
    - 1.17.41.0
    - 1.17.43.0
    - 1.17.44.0
    - 1.17.45.0
    - 1.17.46.0
    - 1.17.47.0
    - 1.17.48.0
    - 1.17.49.0
    - 1.17.5.0
    - 1.17.50.0
    - 1.17.51.0
    - 1.17.52.0
    - 1.17.53.0
    - 1.17.53.1
    - 1.17.54.0
    - 1.17.55.0
    - 1.17.56.0
    - 1.17.57.0
    - 1.17.58.0
    - 1.17.6.0
    - 1.17.7.0
    - 1.17.8.0
    - 1.17.9.0
  - dependency-name: boto3
    versions:
    - 1.16.61
    - 1.16.62
    - 1.16.63
    - 1.17.0
    - 1.17.1
    - 1.17.10
    - 1.17.11
    - 1.17.12
    - 1.17.13
    - 1.17.14
    - 1.17.15
    - 1.17.16
    - 1.17.17
    - 1.17.18
    - 1.17.19
    - 1.17.2
    - 1.17.20
    - 1.17.21
    - 1.17.22
    - 1.17.23
    - 1.17.24
    - 1.17.25
    - 1.17.26
    - 1.17.27
    - 1.17.28
    - 1.17.29
    - 1.17.3
    - 1.17.30
    - 1.17.32
    - 1.17.33
    - 1.17.34
    - 1.17.35
    - 1.17.36
    - 1.17.38
    - 1.17.39
    - 1.17.4
    - 1.17.40
    - 1.17.41
    - 1.17.43
    - 1.17.44
    - 1.17.45
    - 1.17.46
    - 1.17.47
    - 1.17.48
    - 1.17.49
    - 1.17.5
    - 1.17.50
    - 1.17.51
    - 1.17.52
    - 1.17.53
    - 1.17.54
    - 1.17.55
    - 1.17.56
    - 1.17.57
    - 1.17.58
    - 1.17.6
    - 1.17.7
    - 1.17.8
    - 1.17.9
  - dependency-name: chalice
    versions:
    - 1.22.0
    - 1.22.1
    - 1.22.2
    - 1.22.3
  - dependency-name: pydgraph
    versions:
    - 20.7.0
- package-ecosystem: npm
  directory: "/src/js"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: staging
- package-ecosystem: cargo
  directory: "/src/rust"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: staging
  ignore:
  - dependency-name: serde_json
    versions:
    - 1.0.61
    - 1.0.62
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: staging
