[package]
name = "graph-generator-lib"
version = "0.1.0"
authors = ["Insanitybit <insanitybit@gmail.com>"]

[dependencies]

aws_lambda = { git = "https://github.com/srijs/rust-aws-lambda" }

sqs-microservice = {path = "../sqs-microservice"}
graph-descriptions = {path = "../graph-descriptions"}
failure = "0.1.2"

sha2 = "0.7.1"
rusoto_core = "0.32.*"
rusoto_s3 = "0.32.*"
futures = "0.1.23"
base64 = "0.9.2"
prost = "0.4.0"
serde_json = "1.0.24"
rusoto_sqs = "0.32.*"
log = "0.4.3"
base16 = "0.1.1"
zstd = "0.4.21+zstd.1.3.7"
