version: 1
update_configs:
  - package_manager: "submodules"
    directory: "/"
    update_schedule: "daily"
    target_branch: "staging"
  - package_manager: "python"
    directory: "/src/python"
    update_schedule: "daily"
    target_branch: "staging"
  - package_manager: "javascript"
    directory: "/src/js"
    update_schedule: "daily"
    target_branch: "staging"
  - package_manager: "rust:cargo"
    directory: "/src/rust"
    update_schedule: "daily"
    target_branch: "staging"
  - package_manager: "docker"
    directory: "/"
    update_schedule: "daily"
    target_branch: "staging"
