[package]
name = "engagements"
version = "0.1.0"
authors = ["Insanitybit <insanitybit@gmail.com>"]

[dependencies]
serde_derive = "1.0.70"
serde_json = "1.0.24"
dgraph_client = "0.1.0"
uuid = { version = "0.6", features = ["v4"] }
serde = "1.0.70"
incident-graph = {path = "../incident-graph"}