[package]
name = "graph-merger"
version = "0.1.0"
authors = ["Insanitybit <insanitybit@gmail.com>"]

[dependencies]
graph-descriptions = { path = "./graph-descriptions/" }
sqs-microservice = { path = "./sqs-microservice/" }
failure = "0.1.3"
dgraph_client = "0.1.0"
serde = "1.0.80"
serde_json = "1.0.33"
serde_derive = "1.0.80"
int_hash = "0.1.1"
log = "0.4.6"
