[package]
name = "graph-merger"
version = "0.1.0"
authors = ["Insanitybit <insanitybit@gmail.com>"]

[dependencies]
graph-descriptions = { path = "./graph-descriptions/" }
sqs-microservice = { path = "./sqs-microservice/" }
failure = "0.1.3"
serde = "1.0.80"
serde_json = "1.0.33"
serde_derive = "1.0.80"
log = "0.4.6"
#dgraph_client = "*"
dgraph-rs = "0.1.2"
grpc = "0.6.1"
