name: Docker Graph Merger

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
      - staging

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: graph-merger

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build graph-merger
        run: |
          cd ./$IMAGE_NAME/
          mkdir -p ./target/x86_64-unknown-linux-musl/release
          chmod -R 777 ./target
          docker run   -v "$(pwd)":/home/rust/src -t grapl/grapl_rust_base cargo build --release 
          cp "./target/x86_64-unknown-linux-musl/release/$IMAGE_NAME" "./$IMAGE_NAME"
          docker build . -t grapl/grapl-$IMAGE_NAME

      - name: Log into registry
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username grapl --password-stdin

      - name: Push graph-merger

        run: |
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          [ "$VERSION" == "master" ] && VERSION=latest 
          [ "$VERSION" == "staging" ] && VERSION=beta 

          echo $VERSION

          docker tag grapl/grapl-$IMAGE_NAME grapl/grapl-$IMAGE_NAME:$VERSION
          docker push grapl/grapl-$IMAGE_NAME:$VERSION
