name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
      - staging

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: sysmon-subgraph-generator

jobs:

  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build sysmon-subgraph-generator
        run: |
          cd ./sysmon-subgraph-generator/
          mkdir -p ./target/x86_64-unknown-linux-musl/release
          chmod -R 777 ./target
          docker run   -v "$(pwd)":/home/rust/src -t grapl/grapl_rust_base cargo build --release 
          cp "./target/x86_64-unknown-linux-musl/release/sysmon-subgraph-generator" "./sysmon-subgraph-generator"
          docker build . -t grapl/grapl-sysmon-subgraph-generator

      - name: Log into registry
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username grapl --password-stdin

      - name: Push sysmon-subgraph-generator

        run: |
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          
          [ "$VERSION" == "master" ] && VERSION=latest 
          [ "$VERSION" == "staging" ] && VERSION=beta 
          
          docker tag grapl/grapl-sysmon-subgraph-generator:$VERSION
          docker push grapl/grapl-sysmon-subgraph-generator:$VERSION
